# Generated by Django 2.1.1 on 2019-08-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('DES_PIC', 'Opisz zdjęcie'), ('SEL_TRANS', 'Wybierz tłumaczenie')], default='DES_PIC', max_length=30)),
                ('public', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('content', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('categories', models.TextField(blank=True, help_text='gramatyka, czas przeszły', null=True)),
                ('level', models.TextField(blank=True, help_text='A1, A2', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('categories', models.TextField(blank=True, default='', help_text='gramatyka, czas przeszły', null=True)),
                ('level', models.TextField(blank=True, default='', help_text='A1, A2', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='lesson', to='exercises.Exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
