# Generated by Django 2.1.1 on 2019-08-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190828_1610'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordInExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=30)),
                ('highlight_start', models.IntegerField(blank=True, default=0)),
                ('highlight_end', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='variant',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('DES_PIC', 'Opisz zdjęcie'), ('SEL_TRANS', 'Tłumaczenie'), ('PUZ', 'Puzzle'), ('CLICK', 'Naciśnij i zapamiętaj'), ('SORT', 'Sortowanie')], default='DES_PIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='member_of_sets', to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='wordinexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='wordinexercise',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_in_exercises', through='exercises.WordInExercise', to='dictionary.Word'),
        ),
    ]
