# Generated by Django 2.1.1 on 2019-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinexercise',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
