# Generated by Django 2.1.1 on 2019-08-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20190828_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordinexercise',
            name='translation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
