# Generated by Django 2.1.1 on 2019-10-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_wordinexercise_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=30)),
                ('gap', models.IntegerField(blank=True, default=0)),
                ('correct', models.CharField(max_length=30)),
                ('false1', models.CharField(max_length=30)),
                ('false2', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('DES_PIC', 'Opisz zdjęcie'), ('SEL_TRANS', 'Tłumaczenie'), ('PUZ', 'Puzzle'), ('CLICK', 'Naciśnij i zapamiętaj'), ('SORT', 'Sortowanie'), ('SEL_OPT', 'Wybierz opcję')], default='DES_PIC', max_length=30),
        ),
        migrations.AddField(
            model_name='sentence',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='exercises.Exercise'),
        ),
    ]
