# Generated by Django 2.1.1 on 2019-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20191008_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='translation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=100),
        ),
    ]
