# Generated by Django 2.1.1 on 2019-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20191008_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='correct',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='false1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='false2',
            field=models.CharField(max_length=100),
        ),
    ]
