# Generated by Django 2.1.1 on 2019-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20191008_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinexercise',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
