# Generated by Django 2.1.1 on 2019-10-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20191008_1416'),
        ('exercises', '0011_auto_20191008_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordinexercise',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words_in_exercises', to='dictionary.WordIcon'),
        ),
    ]
