# Generated by Django 2.1.1 on 2019-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_wordinexercise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordinexercise',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
