# Generated by Django 2.1.1 on 2019-08-27 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.BooleanField(verbose_name='Konto nauczyciela')),
                ('students', models.ManyToManyField(blank=True, related_name='my_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
