# Generated by Django 2.1.1 on 2018-09-26 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180926_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
