# Generated by Django 2.1.1 on 2019-01-05 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180926_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='my_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
