# Generated by Django 2.1.1 on 2019-08-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0007_auto_20190110_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='tytuł', max_length=30)),
                ('subtitle', models.CharField(blank=True, help_text='podtytuł', max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('text', models.TextField(help_text='zawartość wpisu')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_entries', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='lesson.Exercise')),
            ],
        ),
    ]
