# Generated by Django 2.1.1 on 2019-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190813_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, help_text='zawartość wpisu', null=True),
        ),
    ]
