# Generated by Django 2.1.1 on 2018-09-21 20:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('DES_PIC', 'Opisz zdjęcie'), ('SEL_TRANS', 'Wybierz tłumaczenie')], default='DES_PIC', max_length=30)),
                ('picture', models.ImageField(null=True, upload_to='pictures')),
                ('dictionary', jsonfield.fields.JSONField(blank=True, help_text="[['word','translation'],...]", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='lesson', to='lesson.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='lesson.ExerciseCategory'),
        ),
    ]
