# Generated by Django 2.1.1 on 2018-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20180922_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
