# Generated by Django 2.1.1 on 2018-09-27 22:43

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20180927_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='dictionary',
        ),
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='categories',
            field=models.TextField(blank=True, help_text='B1, gramatyka', null=True),
        ),
    ]
