# Generated by Django 2.1.1 on 2018-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20180928_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='categories',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
