# Generated by Django 2.1.1 on 2019-08-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseasactivity',
            name='exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='exercises.Exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningclass',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises_classes', through='classes.ExerciseAsActivity', to='exercises.Exercise'),
        ),
    ]
