# Generated by Django 2.1.1 on 2019-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190509_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstance',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessoninstance',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
