# Generated by Django 2.1.1 on 2019-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190511_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclass',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='used_in', to='classes.ExerciseInstance'),
        ),
        migrations.AddField(
            model_name='learningclass',
            name='length',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
