# Generated by Django 2.1.1 on 2019-05-13 15:12

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190513_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclass',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='learningclass',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='learningclass',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises_classes', to='lesson.Exercise'),
        ),
        migrations.AlterField(
            model_name='learningclass',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='lesson_classes', to='lesson.Lesson'),
        ),
    ]
