# Generated by Django 2.1.1 on 2019-06-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_auto_20190110_0810'),
        ('classes', '0006_lessoninstance_ex_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),

        migrations.RemoveField(
            model_name='learningclass',
            name='exercises',
        ),
        migrations.AddField(
            model_name='learningclass',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises_classes', through='classes.ExerciseAsActivity', to='lesson.Exercise'),
        ),

        migrations.RemoveField(
            model_name='learningclass',
            name='lessons',
        ),
        migrations.AddField(
            model_name='learningclass',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='lesson_classes', through='classes.LessonAsActivity', to='lesson.Lesson'),
        ),

        migrations.AddField(
            model_name='lessonasactivity',
            name='learning_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.LearningClass'),
        ),
        migrations.AddField(
            model_name='lessonasactivity',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Lesson'),
        ),
        migrations.AddField(
            model_name='exerciseasactivity',
            name='learning_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.LearningClass'),
        ),
    ]
