# Generated by Django 2.1.1 on 2019-07-09 07:35

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20190624_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningclass',
            name='result',
        ),
        migrations.AddField(
            model_name='exerciseasactivity',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='exerciseasactivity',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonasactivity',
            name='ex_status',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='lessonasactivity',
            name='result',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='lessonasactivity',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
