# Generated by Django 2.1.1 on 2019-07-09 12:12

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20190709_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseasactivity',
            name='ex_status',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
