# Generated by Django 2.1.1 on 2019-10-01 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0002_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('start', 'teacher', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('start', 'teacher', 'student')},
        ),
    ]
