# Generated by Django 2.1.1 on 2019-08-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20190828_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='dictionary.WordIcon'),
        ),
    ]
